### ISSUE TITLE
Use the u64 backend by default on x86_64

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/curve25519-dalek#126]
(Branching off of [this comment](https://github.com/rust-lang/rust/issues/35118#issuecomment-377824443) since I think this may be off-topic there)

`curve25519-dalek` has two field arithmetic implementations, a `u32` implementation (using `u64`s for products) and a `u64` implementation (using `u128`s for products). The `u64` backend is selected by the `radix_51` feature, which is selected by the `nightly` feature. Now that `u128`s are stabilizing ([tracking issue](https://github.com/rust-lang/rust/issues/35118)), `u128`s aren't nightly-only. We should:

- [ ] remove the `#![feature(i128_type)]` lines;
- [ ] unlink `radix_51` from `nightly`;
- [ ] make `radix_51` the default feature on `x86_64`.

The last point seems tricky / impossible, since target-specific or target-default features are currently [an open issue in Cargo](https://github.com/rust-lang/cargo/issues/1197).

Features are selected before any code is built, so it's not possible to use architecture-dependent `#[cfg]`s to choose a feature.

One hack (mentioned in the Cargo issue and in the `u128` tracking issue) is to use a `#[cfg]`s in a build script to emit feature selections for the main crate. But this doesn't work for us, because we use the build script to generate constants, so by the time we're in `build.rs` we need to already know which backend to use.

Another approach is to select the backend not by a feature but directly by architecture, or to always use `u128`s, as in https://github.com/ebfull/pairing/issues/80 . 

However, the problem is that just because `u128`s are supported by a target's backend (1) or even lowered to instructions that do a `64 x 64 -> 128` bit multiplication (2) doesn't mean it's better to use them. For (1), if a 64-bit multiplication is going to be emulated by 32-bit multiplications anyways, it would be better just to use them directly, and as an example of (2), `aarch64` has instructions for computing high and low parts of a 128-bit product, but they're not necessarily fast. (This is considering only speed and not safety, like whether emulated multiplications are constant-time).

**Comment by est31** [comment]
> One hack (mentioned in the Cargo issue and in the u128 tracking issue) is to use a #[cfg]s in a build script to emit feature selections for the main crate.

build.rs gets always compiled for the host platform but has to create programs for the target platform. If the two platforms are different (in a cross compilation scenario), the platform build.rs gets built for is different from the platform it has to build stuff for. So don't use `#[cfg]` or `cfg!` in build.rs for that purpose. Instead, build.rs has the `TARGET` env var.

**Comment by hdevalence** [comment]
It seems like the "optimal" thing to do would be something like the following:

- Allow explicit backend selection with `u32`, `u64`, `avx2` features;
- If no backend feature is specified, `build.rs` looks at the `TARGET` env var and makes a best-guess about which backend to use, then emits that feature for the main compilation.

However, because we load the entire crate into the `build.rs` already in order to generate constants using crate-private code, we need to have already selected the target backend **before compiling the build script**.  So the approach above won't work.

**Comment by hdevalence** [comment]
The current status is that the `u64` backend is used by default, and that all backends are selectable with features.

Ideally we would auto-select the backend, but for the reasons described above we can't currently do this.
