### ISSUE TITLE
Efficient multiscalar multiplication for large inputs

### ISSUE THREAD

**Issue by oleganza** [dalek-cryptography/curve25519-dalek#130]
Currently Dalek implements Straus algorithm that scales linearly with number of points. We can use [Pippenger's algorithm](http://www0.cs.ucl.ac.uk/staff/J.Bootle/pippenger.pdf) to scale computation sub-linearly for vectors of more than 200 points.

- [x] Implement Pippenger in vartime
- [x] Implement Pippenger in vartime for AVX2
- [ ] Implement Pippenger in consttime (maybe?)
- [x] Measure the threshold for switching from Straus to Pippenger (today's experiment produced n=190)
- [ ] Measure the thresholds for switching from one window size to another, based on the input size. This may be slightly different for AVX2 and non-AVX2 backends.

**Comment by hdevalence** [comment]
The work in #129 should probably be rebased onto #139 when #139 is done, and then reviewed.

**Comment by isislovecruft** [comment]
Hey @oleganza! Where you at on this? Can I help at all? I don't want to step on your toes, but I do have a bunch of free time due to `$REASON` and I'd be happy to help, including doing whatever cleanup work is needed. :)

**Comment by oleganza** [comment]
Hey, thanks for asking @isislovecruft. I left it off until #139 is sorted out (per Henry's comment on May 14 ^), but after it was shelved, I moved onto other things.

I think the next step would be to address review https://github.com/dalek-cryptography/curve25519-dalek/pull/129 and rebase/merge the latest `develop`.

After that I only need to choose larger window sizes `w` and double-check the `size_hint` threshold for switching from Straus to Pippenger (should be around 190).

In the next few days I won't have much time to deal with that, so would be happy if you could help with that in any way.

**Comment by oleganza** [comment]
Update: going to spend some time today to catch up with PR #129, merge in latest `develop` branch and address Henry's notes.

**Comment by oleganza** [comment]
Update: #129 is ready for review. It's not super-complete (no consttime, no clearondrop), but the core functionality is sorted out and looks good to me.

**Comment by hdevalence** [comment]
Closed by #249. Hurray!
