### ISSUE TITLE
Please document what constant-time guarantees this crate provides

### ISSUE THREAD

**Issue by joshtriplett** [dalek-cryptography/curve25519-dalek#157]
Since this crate provides pure-Rust implementations of cryptographic primitives, the very first question I was trying to find the answer to in the README was whether it had appropriate protection against timing attacks, via constant-time primitives. (And, if so, how it managed to do so using pure Rust code.)

After some digging, it *looks* like this crate does use appropriate constant-time operations through the `subtle` crate. That crate, in turn, mentions the need to use the `nightly` feature for full protection.

Could you please document, in the README for both this crate and the ed25519/x25519 crates (either directly or via a link), the timing-attack resistance and constant-time properties, and in particular the requirement to use the `nightly` feature to fully achieve those properties?

Thank you for your work on these crates; much appreciated.

**Comment by hdevalence** [comment]
Hi, we already have a description of the safety guarantees in a branch (part of the pre-1.0 work we're doing), it's just not merged yet. I'll close this issue when those changes get merged into the `develop` branch.

Use of the `nightly` feature only adds additional safeguards that are only possible using Rust; without it, we get exactly the same properties as are available to C implementations. So while the `nightly` feature is recommended, it is not required to achieve the same properties as an alternative implementation written in C.

**Comment by joshtriplett** [comment]
@hdevalence From what I can tell, it looks like the `nightly` feature in `subtle` is (currently) required to prevent the optimizer from breaking the constant-time guarantees, in the same way that C can achieve through things like `volatile` or passing through an asm block just like Rust can.

**Comment by isislovecruft** [comment]
In #162 @hdevalence documented more w.r.t. constant-time guarantees, but if anything is still unclear please feel welcome to re-raise this issue.

**Comment by joshtriplett** [comment]
Those changes cover it, thank you!
