### ISSUE TITLE
AVX2 build broken due to deletion of `core::simd` upstream

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/curve25519-dalek#175]
The `core::simd` module was deleted last week (discussion: https://github.com/rust-lang-nursery/stdsimd/issues/525), so the AVX2 backend won't build any more.

For now it's possible to fix the build by setting last week's nightly in `rust-toolchain`:
```
echo "nightly-2018-07-19" > rust-toolchain
```

**Comment by hdevalence** [comment]
https://github.com/rust-lang-nursery/stdsimd/issues/539

**Comment by gnzlbg** [comment]
Are there any open issues with the migration?

**Comment by hdevalence** [comment]
Nope, this should have been closed by #178, sorry about that! Thanks for publishing a crate so fast, I was worried that it had been removed to be redesigned, and that the crate wouldn't be ready for a while.
