### ISSUE TITLE
Are there any performance bugs that prevent the usage of shuffle! in the AVX2 backend?

### ISSUE THREAD

**Issue by gnzlbg** [dalek-cryptography/curve25519-dalek#181]
I just read a blog post about this library and was wondering why does the AVX2 backend do not use the `shuffle!` macro instead of the many other intrinsics for re-ordering vector elements. 

If there are any performance issues with it, it would really help if bugs could be filled in packed_simd upstream.

**Comment by gnzlbg** [comment]
Duh... the `shuffle!` macro was never merged into `std::simd` because of problems with exporting macros from `core`/`std`... so I guess that's the reason.

**Comment by gnzlbg** [comment]
Looking at the code, the shuffle macro just takes a constant vector of indices. 

I think that you might be able to keep using the `AAAA` notation with `shuffle!` by doing something like:

```rust
const AAAA: [i32; 4] = [0, 0, 0, 0];
shuffle!(vec, AAAA);

**Comment by hdevalence** [comment]
Closing this for now just because I don't have any plans to refactor the AVX2 backend right now; it could be reopened later.
