### ISSUE TITLE
Bump byteorder version?

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/curve25519-dalek#184]
We may need/want to bump the byteorder version to avoid this problem with `#[feature]`s, pointed out by @ruuda: https://github.com/dalek-cryptography/curve25519-dalek/commit/1e74cb3e56c1b2dba7d72b5bf8ed69c094417e0b#r29958498

**Comment by isislovecruft** [comment]
@mimoo also pointed this out on slack

**Comment by isislovecruft** [comment]
#186 is one way to fix this.

**Comment by hdevalence** [comment]
Looking through the byteorder versions, it seems like `1.2.3` was the first version that didn't include a `#[feature(...)]` gating (which is what causes the problem).  It's a little unfortunate that it wasn't a minor version bump to `1.3`, but I think that just specifying
```
byteorder = "^1.2.3"
```
should fix the problem.
