### ISSUE TITLE
Does not build for `no_std` thumb target

### ISSUE THREAD

**Issue by jamesmunns** [dalek-cryptography/curve25519-dalek#187]
Although no_std support is listed, this crate fails to compile for a no_std thumb (microcontroller) target.

See https://gist.github.com/jamesmunns/22476dc78dba3f231b0c15b5d82261a8

This is likely the cause of https://github.com/dalek-cryptography/ed25519-dalek/issues/35.

**Comment by jamesmunns** [comment]
CC @aep

**Comment by tarcieri** [comment]
Are you encountering this problem:

https://tonyarcieri.com/rust-in-2019-security-maturity-stability#bad-interactions-between-code-classprettyprin_2

My preferred open bug for it:

https://github.com/rust-lang/cargo/issues/4866

**Comment by nickray** [comment]
Wow, thanks Tony! Indeed, throwing out all the dev-dependencies lets the build succeed. Also thanks for clear pointers to that issue I had somewhere in the back of my mind, but no good reference...

As I understand it:
- both bincode and criterion pull in std, the bug you mentioned triggers the problem
- I'd speculate on targets that do have std the no-std builds still pull in std

@jamesmunns in a sense this solves this issue and https://github.com/dalek-cryptography/ed25519-dalek/issues/35

**Comment by hdevalence** [comment]
It seems like the issue was identified as the upstream Cargo issue; I'm closing this for now but feel free to open a new issue if there are further problems.

**Comment by tarcieri** [comment]
In particular you'll want to ensure your `build-dependencies` and `dev-dependencies` do not activate the `std` features of `byteorder` and `rand_core`

**Comment by cheme** [comment]
Also please notice that `clear_on_drop` is breaking no_std (zeroize might be an alternative), and`rand_core` need update.

**Comment by hdevalence** [comment]
@cheme what's the problem with `clear_on_drop`? I've got it to cross-compile to ARM in no_std mode before, the only catch is that without the `nightly` feature it requires a C compiler.

**Comment by cheme** [comment]
Mistake from my part (just retested it), please forget it.

**Comment by hdevalence** [comment]
No worries, I've personally run into that problem with `clear_on_drop` before, which is why I thought of it :)

In the future it would be good to use `Zeroize` but my personal inclination would be to wait until after its `1.0` release, because unlike `clear_on_drop` it's public API so using it once is committing to it forever.
