### ISSUE TITLE
Add `impl Mul<Scalar> for {Edwards,Ristretto}BasepointTable`?

### ISSUE THREAD

**Issue by isislovecruft** [dalek-cryptography/curve25519-dalek#194]
It's only implemented for borrows currently.

**Comment by hdevalence** [comment]
IIRC the reasoning for adding the operators for non-borrowed points was that the points were pretty small in the grand scheme of things and so copying them wasn't a big deal. But the basepoint tables are large, so it seems like encouraging people to use borrows of them is probably better?
