### ISSUE TITLE
Scalar should implement `subtle::ConditionallySelectable`

### ISSUE THREAD

**Issue by cathieyun** [dalek-cryptography/curve25519-dalek#200]
Since `ConditionallySelectable` is a root trait for other subtle traits, `Scalar` should implement `ConditionallySelectable`.

This is relevant for implementing constant-time equality checking in the bulletproofs circuit code: https://github.com/dalek-cryptography/bulletproofs/pull/166

**Comment by cathieyun** [comment]
I also filed an issue on the `subtle` crate to clarify the docs:
dalek-cryptography/subtle#36

**Comment by hdevalence** [comment]
Closed by #205
