### ISSUE TITLE
Unconditionally clear `Scalar`s with a `Drop` impl

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/curve25519-dalek#208]
We should implement `Drop` for `Scalar`s and wipe their storage unconditionally, so that downstream users don't need to worry about clearing secret scalars themselves.

@isislovecruft originally suggested this a while ago, and I thought it wasn't a good idea because it would be wiping both secret and non-secret `Scalar`s, but the overhead is really small and it makes a lot of things easier, so I think they were correct originally.

**Comment by DebugSteven** [comment]
Hey I'm already doing this in x25519 I can do so here also.

**Comment by DebugSteven** [comment]
Removing `Copy` for `Scalar`s is a breaking change. What do you want to do instead?

**Comment by hdevalence** [comment]
Ah, `Drop` types can't be `Copy`. Removing `Copy` makes using the `ops` traits really unergonomic ... maybe that was the reason for not implementing `Drop`, I don't really remember.

I'm not sure what to do for `curve25519-dalek` (cc @isislovecruft ?), so maybe the best thing to do is to wait on making any changes here, and just do them in x25519 for now?

**Comment by hdevalence** [comment]
Closing this since `Copy` can't `Drop`; we could consider adding a new scalar type that dropped its contents.
