### ISSUE TITLE
Derive additional traits for `CompressedRistretto` / `CompressedEdwardsY`

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/curve25519-dalek#221]
Branching off of #220, specifically https://github.com/dalek-cryptography/curve25519-dalek/pull/220/commits/3e91ba023b6b836b5cbbb10419252314e8937c73 , where @burdges suggested adding
```
#[derive(Ord, PartialOrd, Hash)]
```
to `CompressedRistretto`.  This allows using a `CompressedRistretto` as the key to a `BTreeMap`, which [requires `Ord`](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html) (hence `PartialOrd`), and with `HashMap`, which [requires `Hash`](https://doc.rust-lang.org/std/collections/struct.HashMap.html). 

This seems like a useful use-case, for instance looking up information by a public key.

Some questions that would be good to cross off answers to:

* Does it make sense to derive `Ord` for encodings of points? Unlike scalars, there's no meaningful ordering on points, so we could only do something like ordering the bytestrings.

* Does it make sense to do this also for `CompressedEdwardsY` as well as `CompressedRistretto`? In particular, is there any potential for ambiguity/non-uniqueness?

* Is there a problem with using the derived implementations? For instance, if we derive `Hash`, will it do something like hash one byte at a time?

* What's the stability impact of adding new derives? I think this is probably fine (it's just adding new traits) but we should check.

**Comment by burdges** [comment]
I never suggested this for `CompressedEdwardsY` out of anti-cofactor prejudice, but actually the cofactor could be managed reasonably for at least multi-signatures, so sure whatever.  

I think these derives produce very thin wrappers, so the question boils down to `[u8;32]`:

In this case, [`impl Hash for [T; 32]`](https://doc.rust-lang.org/src/core/array.rs.html#180-184) delegates to [`impl Hash for [T]`](https://doc.rust-lang.org/src/core/hash/mod.rs.html#663-668) which uses `<T as Hash>::hash_slice`, for which [`u8` does the right thing](https://doc.rust-lang.org/src/core/hash/mod.rs.html#570).  

Also [`impl PartialOrd for [T; 32]`](https://doc.rust-lang.org/src/core/array.rs.html#225-246) delegates to [`impl PartialOrd for [T]`](https://doc.rust-lang.org/src/core/slice/mod.rs.html#4878-4882), which used [`SlicePartialOrd`](https://doc.rust-lang.org/src/core/slice/mod.rs.html#4958) and [`SliceOrd`](https://doc.rust-lang.org/src/core/slice/mod.rs.html#4972)

**Comment by hdevalence** [comment]
Closed by #318.
