### ISSUE TITLE
Make Ristretto constants actually constants

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/curve25519-dalek#224]
The Ristretto Elligator map uses constants which are computed on every run, instead of being loaded as constants.

The lines can be found in this part of the `develop` branch: https://github.com/dalek-cryptography/curve25519-dalek/blob/develop/src/ristretto.rs#L580-L581

These constants should be extracted into `backend/u32` and `backend/u64`. Doing this requires dumping the limb values. Since field elements implement `Debug`, this could be done just by adding some `println!`s, getting the limb values, putting them into the source code, and then removing the printlns.

**Comment by isislovecruft** [comment]
Fixed in #301. Thanks @VictorKoenders!
