### ISSUE TITLE
Trait bounds for `random` functions in `1.1`

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/curve25519-dalek#232]
`1.1` changed the trait bounds for `RistrettoPoint::random` and `Scalar::random`, see #222 and #219.

These changes have two benefits:
* they unlink us from the `rand` crate and make us depend only on `rand_core`;
* they allow passing both owned and borrowed RNGs.

The change was not supposed to be a breaking change, since the new bounds are strictly more general than the old ones (as every `RngCore` is an `Rng` and every `&mut RngCore` is an `RngCore`), so the new bound is satisfied in every situation where the old bound applied.

The `1.1.0-pre.0` version didn't cause problems on the crates I tested it on, but there was an unexpected problem: https://github.com/interstellar/slingshot/blob/ce71c93a9a29ac3b4f69ce71feb987bd64d6c4ec/spacesuit/src/value.rs#L160-L161 broke, since it took a borrow as input and used it twice. So there was slight breakage.

One option is to revert the changes (probably just the ones from #219) and release 1.1.3; another would be to fix up `slingshot` and leave the new bound.

**Comment by oleganza** [comment]
Here's my fix, for reference: https://github.com/interstellar/slingshot/pull/89

**Comment by hdevalence** [comment]
My feeling is that it would be better to revert #219 in 1.1.3, so that there's no potential for future problems. We will have to release a 2.0 eventually once the `rand` crate is stabilized, so if we wanted to change it then we could do it then.

**Comment by hdevalence** [comment]
Closing this since it was fixed in #233
