### ISSUE TITLE
Add a doc feature that pulls in packed_simd

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/curve25519-dalek#253]
Moving here from https://github.com/dalek-cryptography/x25519-dalek/issues/42

**Comment by hdevalence** [comment]
This is connected to #256 because it involves rearranging the `cfg` statements, so it should be done after #256, which is currently blocked.

**Comment by hdevalence** [comment]
It seems like something changed with rustdoc to break (the way we are using) `doc_cfg`, so the docs for the SIMD backend internals are broken. I'm not sure what the problem was but hopefully it can be fixed as part of this issue.

**Comment by isislovecruft** [comment]
Closing as we use a new `packed_simd_2` crate now and I'm not certain if this is still an issue. If it turns out to be when I get around to fixing the documentation website, I'll reopen.
