### ISSUE TITLE
u32_backend doesn't compile on Ubuntu

### ISSUE THREAD

**Issue by trevp** [dalek-cryptography/curve25519-dalek#264]
Below is the failing cargo build command, and info on Rust and Ubuntu versions.

$ cargo test --features u32_backend
   Compiling curve25519-dalek v1.2.1 (/home/trevor/code/rust/curve25519-dalek)
error[E0428]: the name `UnpackedScalar` is defined multiple times
   --> src/scalar.rs:178:1
    |
171 | type UnpackedScalar = backend::serial::u64::scalar::Scalar52;
    | ------------------------------------------------------------- previous definition of the type `UnpackedScalar` here
...
178 | type UnpackedScalar = backend::serial::u32::scalar::Scalar29;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `UnpackedScalar` redefined here
    |
    = note: `UnpackedScalar` must be defined only once in the type namespace of this module

 cargo test --features u32_backend
   Compiling curve25519-dalek v1.2.1 (/home/trevor/code/rust/curve25519-dalek)
error[E0428]: the name `UnpackedScalar` is defined multiple times
   --> src/scalar.rs:178:1
    |
171 | type UnpackedScalar = backend::serial::u64::scalar::Scalar52;
    | ------------------------------------------------------------- previous definition of the type `UnpackedScalar` here
...
178 | type UnpackedScalar = backend::serial::u32::scalar::Scalar29;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `UnpackedScalar` redefined here
    |
    = note: `UnpackedScalar` must be defined only once in the type namespace of this module

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

$ rustup show
Default host: x86_64-unknown-linux-gnu

stable-x86_64-unknown-linux-gnu (default)
rustc 1.36.0 (a53f9df32 2019-07-03)

**Comment by hdevalence** [comment]
Hmm, it looks like both the `u64_backend` and `u32_backend` features are enabled.  The `u64_backend` is enabled by default because until #217 is fixed, we can't auto-select the backend in the `build.rs` itself.

Does the problem still occur with `cargo test --no-default-features --features "u32_backend std"`?

**Comment by trevp** [comment]
No, with `cargo test --no-default-features --features "u32_backend std"` it compiles and tests successfully.
