### ISSUE TITLE
Panic in non_adjacent_form while w>=7

### ISSUE THREAD

**Issue by 3for** [dalek-cryptography/curve25519-dalek#272]
Changing the test code from `5` to `7`, an error occurred.
```
#[test]
    fn non_adjacent_form() {
        let naf = A_SCALAR.non_adjacent_form(7); // 7 instead of 5.
        for i in 0..256 {
            assert_eq!(naf[i], A_NAF[i]);
        }
    }
```
![image](https://user-images.githubusercontent.com/30716372/62451205-5f1e9180-b7a0-11e9-835f-a906b94da843.png)
It seemed that the code line in `non_adjacent_form` should changed:
```
//naf[pos] = (window as i8) - (width as i8);
naf[pos] = (window as i8).wrapping_sub(width as i8); // Fix panic error
```

**Comment by 3for** [comment]
Another question is that:
Would it be better to change ` let mut x_u64 = [0u64; 5];  if bit_idx < 64 - w {` to ` let mut x_u64 = [0u64; 4];  if bit_idx < 64 - w || u64_idx == 3  {` for memory saving?

**Comment by hdevalence** [comment]
Seems bad, I'll take a look.  I don't think that saving 8 bytes of stack space really matters, but this code shouldn't panic.
