### ISSUE TITLE
Confusing with `INVSQRT_A_MINUS_D` value?

### ISSUE THREAD

**Issue by 3for** [dalek-cryptography/curve25519-dalek#280]
I'm confusing with the `INVSQRT_A_MINUS_D`, why it's  `54469307008909316920995813868745141605393597292927456921205312896311721017578` (bigger number) instead of `3426737609748780790789678635598812321241395039892825098523479107644843802371`(smaller number)?

Though, the compressing schedule is to get the absolute value. And I've tested both values work the same.

```
sage: p=2^255-19
sage: d=mod(-121665/121666,p)
sage: d
37095705934669439343138083508754565189542113879843219016388785533085940283555
sage: a=mod(sqrt(-1-d),p)
sage: a
25063068953384623474111414158702152701244531502492656460079210482610430750235
sage: mod(1/a,p)
3426737609748780790789678635598812321241395039892825098523479107644843802371
sage: mod(-1/a,p)
54469307008909316920995813868745141605393597292927456921205312896311721017578
```

**Comment by hdevalence** [comment]
The conventional definition of sign for the finite field Z/p is that x is negative if the low bit of the least nonnegative integer representative is set. See here for the exact check: https://github.com/dalek-cryptography/curve25519-dalek/blob/master/src/field.rs#L73-L83

I believe that the current constant was chosen to be the nonnegative square root, with this definition of negativity.
