### ISSUE TITLE
Outdated crate version in public doc

### ISSUE THREAD

**Issue by alxiong** [dalek-cryptography/curve25519-dalek#309]
Currently in [public doc](https://doc.dalek.rs/curve25519_dalek/index.html#use), it is out of sync with the README file in this repo. 

1. change `curve25519-dalek = "1"` to `curve25519-dalek = "2"`, (otherwise `Scalar::random()` will complain about any Rng from `rand*` crate for not implementing the `rand_core::RngCore, CryptoRng` trait)
2. prefer `use curve25519_delak;` over `extern crate curve25519_dalek;`

thanks!

**Comment by hdevalence** [comment]
Hi, it looks like the deploy pipeline for the custom docs broke, so the current docs aren't being deployed.  I am working on fixing it now.  In the meantime https://docs.rs/curve25519-dalek has the current docs.

**Comment by hdevalence** [comment]
Fixed!
