### ISSUE TITLE
RistrettoPoint from EdwardsPoint

### ISSUE THREAD

**Issue by mikhailOK** [dalek-cryptography/curve25519-dalek#313]
Our use case requires converting an `EdwardsPoint` to `RistrettoPoint`, but seems like there is no public way to do it. 
Current workaround is this: 
```let rp: RistrettoPoint = unsafe { transmute(ep) };```

It would be nice to have something like `RistrettoPoint::TryFrom<EdwardsPoint>` that checks `is_torsion_free`.

**Comment by hdevalence** [comment]
Yup, there's no API for that because you are not supposed to convert an Ed25519 point to a Ristretto point.

**Comment by WildCryptoFox** [comment]
@mikhailOK Can you explain why you believe the functionality is required? Are you trying to reuse a key between contexts?

**Comment by mikhailOK** [comment]
@WildCryptoFox exactly, we're trying to use the same key for signatures and a scheme that uses ristretto group

**Comment by WildCryptoFox** [comment]
@mikhailOK Please avoid reusing keys between protocols, especially with different groups. The analysis is non-trivial and rarely worth it. Can you use Ristretto for both or decide which is used by stashing a bit to decide between the two groups?
