### ISSUE TITLE
Printing a pre-computed lookup table of base multiples for Ed25519

### ISSUE THREAD

**Issue by eikendev** [dalek-cryptography/curve25519-dalek#324]
Hi there,

I'm currently experimenting with my own Ed25519 implementation, and would like to achieve some speedup using a pre-computed lookup table. I wanted to use `curve25519-dalek` to generate the table.

Note that the goal is to lookup base point multiples only, and ideally I would like to have a version containing the points in affine and extended representations.

I had a look at both the `EdwardsPoint` and `EdwardsBasepointTable` structs, but neither seems to support outputting the contents of the points, except for conversion into the compressed format. Of course I could print the points via the `Debug` trait and parse the output, but this just doesn't seem like it's the right way to go.

I think that either I overlooked something, or this truely isn't supported, but I'm not sure which is the case.

**Comment by hdevalence** [comment]
Yep, this isn't supported.  Since the pre-computed lookup tables aren't exposed as part of the public API, you need to hook into the library internals to access them anyways, so you could either use the `Debug` output or patch the library locally.
