### ISSUE TITLE
Incorrect = depedency in 1.2.3

### ISSUE THREAD

**Issue by nmccarty** [dalek-cryptography/curve25519-dalek#328]
My company depends transitively on this crate through version 0.9.1 of `ed25519-dalek`.

Recently, with the inline assembly changes in rustc, the [`=0.2.3` dependency](https://github.com/dalek-cryptography/curve25519-dalek/blob/4dc8073330f63fb23040f7aa7dd0159aac7a9923/Cargo.toml#L50) on `clear_on_drop` has left us trapped on old nighties, as the `=` dependency leaves us unable to upgrade to recently released `clear_on_drop v0.2.4` .

Would it be possible to get another release of the 1.x.x branch rolled that changes this line from

```toml
clear_on_drop = "=0.2.3"
```

to 

```toml
clear_on_drop = "0.2"
```

**Comment by hdevalence** [comment]
Sorry to hear about that.  I pushed commit 4ed5c1b to a `release/1.x` branch.  Before I publish it as 1.2.4, would it be possible for you to test it using a [patch directive](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section)?

**Comment by nmccarty** [comment]
Thank you for making that change, however it only appears you got the one in the `build-dependencies` section, the one in `depedencies` is still `=0.2.3`.

**Comment by hdevalence** [comment]
Oops, my bad, try 1faf618 ?

**Comment by nmccarty** [comment]
The revised commit appears to have done the trick, and we are up and running on the latest nightly with it. Thank you!

**Comment by hdevalence** [comment]
Great, I'll release it as 1.2.4.

**Comment by hdevalence** [comment]
1.2.4 should be on crates.io and it should be possible to remove the `patch` directive now. Please reopen this issue if that doesn't work!
