### ISSUE TITLE
Question: Is it safe to use the same keypair with x25519-dalek and ed25519-dalek ?

### ISSUE THREAD

**Issue by fungiboletus** [dalek-cryptography/curve25519-dalek#331]
Hi, I have a beginner question.

I want to use curve25519 to encrypt with x25519-dalek (and then xchacha20poly1305) or sign with ed25519-dalek, and I'm wondering whether it's safe or even possible to use the same keypair.

Thanks.

**Comment by tarcieri** [comment]
Some previous discussion: https://github.com/dalek-cryptography/ed25519-dalek/issues/118

**Comment by fungiboletus** [comment]
Thanks for the link.

> we have a sort of political opinion that using the same keypair for multiple protocols is bad practice and should be avoided at all costs.

That answers my question, I will generate two keypairs.
