### ISSUE TITLE
Forbid unsafe code

### ISSUE THREAD

**Issue by ralpha** [dalek-cryptography/curve25519-dalek#332]
`curve25519-dalek` ~~does not seem to use unsafe code, which is very good :)~~

To prevent this from ever happening, add following line to the top:
```rust
#![forbid(unsafe_code)]
```
of https://github.com/dalek-cryptography/curve25519-dalek/blob/master/src/lib.rs

This will make the package green in 
https://github.com/rust-secure-code/cargo-geiger

EDIT: It seems that the crate DOES use unsafe code.
This code just happens not be triggered in my use-case/code-base.
```
0/2        0/857        0/0    0/0     0/0      ?  ├── curve25519-dalek 3.0.0
```
So adding the `forbid` flag will not work in this crate. (unless the unsafe code is replaced)
So this can be closed unless these unsafe features are used under cfg feature flags.

**Comment by hdevalence** [comment]
This crate (optionally) uses AVX2 intrinsics for vectorized multiplication.  There's no risk to memory safety.

**Comment by WildCryptoFox** [comment]
@hdevalence If this is the only permitted use of `unsafe` then you may use `#![cfg_attr(not(feature = "avx2_backend"), forbid(unsafe_code)]` to reflect this.
