### ISSUE TITLE
Implement elliptric-curve traits

### ISSUE THREAD

**Issue by daxpedda** [dalek-cryptography/curve25519-dalek#373]
I propose implementing some of the traits defined in [elliptic-curve](https://crates.io/crates/elliptic-curve) to improve compatibility with downstream users.

Specifically [`Group`](https://docs.rs/elliptic-curve/0.10.6/elliptic_curve/trait.Group.html), [`GroupEncoding`](https://docs.rs/group/0.11.0/group/trait.GroupEncoding.html) and [`Field`](https://docs.rs/elliptic-curve/0.10.6/elliptic_curve/trait.Field.html) is what I had in mind.

I'm working on a PR as we speak.

**Comment by kayabaNerve** [comment]
Is there any chance this will be done for EdwardsPoint as well (perhaps in another PR)? I don't believe group has the necessary functions to handle torsion, which would explain why it's not being done in that PR, yet it should at least be possible to provide group bindings with a main subgroup requirement. That may be a higher level decision than desired (see discussion on https://github.com/dalek-cryptography/curve25519-dalek/issues/380), yet my current workaround is my own library stubbing out parts of ff/group as needed (with a main subgroup check when decoding). I'd really love to be able to delete it in favor of this PR (or a relative), yet unfortunately do need to work with Ed25519.

Even if no one's willing to step up to the plate to handle this right now, I would be curious if such a PR would be accepted.

**Comment by daxpedda** [comment]
I believe this can be closed now that https://github.com/dalek-cryptography/curve25519-dalek/pull/562 is merged?

**Comment by rozbb** [comment]
Yup!
