### ISSUE TITLE
update rand_core to 0.6.0

### ISSUE THREAD

**Issue by alxiong** [dalek-cryptography/curve25519-dalek#376]
Hi, 

Would you please consider upgrading `rand_core` dependency to `0.6.0`, because some other dependencies we use are depending on `rand 0.8.4` -> `rand_core 0.6.0` and `RngCore + CryptoRng` are not compatible.

Thanks!

**Comment by weikengchen** [comment]
I also encounter this similar issue. Let me create a PR. 

As this is a breaking change, this would likely be part of 0.4.0.

**Comment by weikengchen** [comment]
It seems that the issue has been solved. One just needs to use `4.0.0-pre.1`.

**Comment by piegamesde** [comment]
Since people are likely going to be stuck on version 3 for a while until the bump propagates through the ecosystem — can this please be backported?
