### ISSUE TITLE
Old version of zeroize

### ISSUE THREAD

**Issue by iupii** [dalek-cryptography/curve25519-dalek#387]
curve25519-dalek requires zeroize < 1.4, but a lot of crates already depend on 1.4.1 etc.
Any plans to bump zeroize deps?

**Comment by tarcieri** [comment]
See #362 and #386

**Comment by 0xdeafbeef** [comment]
Any updates?

**Comment by rozbb** [comment]
This is now resolved in the release/4.0 branch. Next release (or prerelease) will have a laxer zeroize dependency.

**Comment by nox** [comment]
@tarcieri @rozbb Doesn't zeroize now have a MSRV policy? Why keep using upper bounds for the zeroize dependency then?

**Comment by nox** [comment]
Disregard that, I'm a moron and I was not actually looking at the right branch.
