### ISSUE TITLE
Remove dependencies

### ISSUE THREAD

**Issue by xpepermint** [dalek-cryptography/curve25519-dalek#392]
I believe that lower-level libraries such as this one should be dependency-free. This is especially true for libraries that provide "delicate" features such as encryption. I see lots of dependencies listed in the `Cargo.toml` file which IMHO aren't crucial and should be wrapped into optional features or even extracted into smaller specialized crates.

@isislovecruft @cathieyun

**Comment by k0nserv** [comment]
per @piegamesde's comment I got rid of `byteorder` in https://github.com/dalek-cryptography/curve25519-dalek/pull/418

**Comment by rozbb** [comment]
Fixed!
