### ISSUE TITLE
Positive integer to Ristretto point and back

### ISSUE THREAD

**Issue by jimouris** [dalek-cryptography/curve25519-dalek#410]
Hi,

Is there a way to convert a `u32` (or `u64` or a vector of `u8`) to a Ristretto point and then back without hashing (`RistrettoPoint::hash_from_bytes::<Sha512>(text.as_bytes())`)?

I'm implementing ElGamal encryption with elliptic curves and I do not want to hash my message. Essentially, I want something like:
```
to_point(text: &[u8]) -> RistrettoPoint
from_point(pt: RistrettoPoint) -> [u8]
```

Thank you!

**Comment by donkey-donkey** [comment]
anyone know of a way besides brute force? its sooo slow.
```
let val1 = 545212u64;
let message1: RistrettoPoint = &Scalar::from(val1) * &GENERATOR_TABLE;

 let mut scalar = Scalar::zero();
    let mut point = RistrettoPoint::default();
    while point != message1 {
        scalar += Scalar::one();
        point = &scalar * &GENERATOR_TABLE;
    }
    // Now scalar should be the original scalar. You can convert it into a u64:
    let original_u64: u64 = u64::from_le_bytes(scalar.to_bytes()[..8].try_into().unwrap());
```

**Comment by tarcieri** [comment]
Converting a Ristretto point to a scalar would involve solving the Discrete Logarithm Problem, the hard problem which underlies its security.

With a `u32` target you could potentially mount a more efficient attack than you’re doing using something like Pollard’s Rho algorithm, you’d be much better off using a construction that doesn’t require solving DLP.

**Comment by rozbb** [comment]
I found [one option](https://eprint.iacr.org/2013/373.pdf) (section 2.4). The idea is you pick a random x-coordinate whose low 32-bits are your message, and you find the corresponding y if one exists. If non exists, try with another x. You can probably do this using the existing `MontgomeryPoint` type and its `to_edwards` method. Does that make sense?

**Comment by donkey-donkey** [comment]
> I found [one option](https://eprint.iacr.org/2013/373.pdf) (section 2.4). The idea is you pick a random x-coordinate whose low 32-bits are your message, and you find the corresponding y if one exists. If non exists, try with another x. You can probably do this using the existing `MontgomeryPoint` type and its `to_edwards` method. Does that make sense?

this is a very cool idea. like steganography. however afaik it doesn't allow homomorphic properties.

**Comment by rozbb** [comment]
Correct. I believe you have to do dlog-based inversion if you want the homomorphic property

**Comment by donkey-donkey** [comment]
> Converting a Ristretto point to a scalar would involve solving the Discrete Logarithm Problem, the hard problem which underlies its security.
> 
> With a `u32` target you could potentially mount a more efficient attack than you’re doing using something like Pollard’s Rho algorithm, you’d be much better off using a construction that doesn’t require solving DLP.

thanks. i will looki into the Pollard's Rho. 
we are exploring as many construction ideas as we can find that support HE.

**Comment by rozbb** [comment]
Great. Closing for now
