### ISSUE TITLE
`simd_backend`: replace `packed_simd_2` with `std::simd`

### ISSUE THREAD

**Issue by tarcieri** [dalek-cryptography/curve25519-dalek#415]
The `packed_simd_2` crate used by the `simd_backend` feature is a prototype of `std::simd`, which has since landed in the nightly compiler, making `packed_simd_2` effectively obsolete.

It would probably be a good idea to migrate `simd_backend` to use `std::simd`.

**Comment by rozbb** [comment]
Looked into this and it seems like a pretty nontrivial change. Some traits aren't implemented (e.g., going from `Simd<u32, 8>` to a `Simd<u64, 4>`), shifting like `Shl<u8> for Simd<u64, 4>`, and extracting lanes `Simd<u32, 8>::extract`.

Maybe it'd be best to move this out of the way for 4.0?

**Comment by tarcieri** [comment]
Sure

**Comment by tarcieri** [comment]
I consider this addressed by #520.

An eventual migration to `std::simd` would probably make sense, but in the meantime, this has removed the `pack_simd_2` dependency.
