### ISSUE TITLE
Run rustfmt

### ISSUE THREAD

**Issue by rozbb** [dalek-cryptography/curve25519-dalek#416]
A lot of this crate uses nonstandard formatting. If you edit files in an IDE with rustfmt-on-save, then you end up getting diffs that are way bigger than necessary. This crate should either have a `rustfmt.toml` or use the default formatting rules, and then apply them crate-wide.

**Comment by tarcieri** [comment]
+1 for the default rules.

When running rustfmt for the first time I’d suggest keeping a lookout for large blocks/tables where rustfmt results in worse formatting and annotating those with `#[rustfmt::skip]`

**Comment by rozbb** [comment]
Closed in #424
