### ISSUE TITLE
Use `#![doc = include_str!("../README.md")]`

### ISSUE THREAD

**Issue by tarcieri** [dalek-cryptography/curve25519-dalek#426]
`src/lib.rs` contains large blocks of copy/paste from README.md.

The `#![doc = include_str!("../README.md")]` directive can be used to include the README.md in the rustdoc, eliminating the duplication, and ensuring all code examples in README.md are also doctested.

**Comment by pinkforest** [comment]
#429 was merged so this can be closed as Resolved
