### ISSUE TITLE
Allow `fiat_backend` and `simd_backend` to be activated at the same time

### ISSUE THREAD

**Issue by tarcieri** [dalek-cryptography/curve25519-dalek#437]
Right now `fiat_backend` and `simd_backend` are mutually exclusive: activating both crate features generates a compile error.

In #414 we discussed various alternatives including something like `--cfg dalek_backend="simd"`. However, since the backends map to optional crate dependencies, features seem like a more natural fit.

As an alternative to a compile error, another option would be to handle the case of both features being activated by choosing a "winner" backend which is selected when both options are enabled.

[In #414 I suggested that given various tradeoffs, it should probably be `fiat_backend`](https://github.com/dalek-cryptography/curve25519-dalek/issues/414#issuecomment-1316167153) because it would be bad to enable a non-verified backend when someone has asked for a formally verified one (even though `simd_backend` is superior in pretty much all other respects).

This isn't a blocker for a v4.0 release though, as it can easily be added afterward as it changes a case which is currently a compile error into one that works.

**Comment by pinkforest** [comment]
Should fiat be`cfg(curve25519_dalek_serial  "fiat")`

**Comment by pinkforest** [comment]
PR's up:
- https://github.com/dalek-cryptography/curve25519-dalek/pull/463

**Comment by pinkforest** [comment]
So the above PR was my confusion - This was really resolved by #455 - https://github.com/dalek-cryptography/curve25519-dalek/pull/463#issuecomment-1344362036

This issue should be closed probably.
