### ISSUE TITLE
SemVer policy for pre-1.0 dependencies

### ISSUE THREAD

**Issue by tarcieri** [dalek-cryptography/curve25519-dalek#442]
Something I think should be documented prior to the 4.0 release is the SemVer policy for pre-1.0 dependencies which are part of the public API, namely `digest` and `rand_core`.

I would suggest exempting these APIs from SemVer guarantees around major versions, allowing them to be updated with a minor version bump only.

It might be worth considering making both of those dependencies optional and noting if they're activated, you're opting into something which isn't stable around major versions. That would mean the feature profile one receives with the default features activated *is* stable around major versions.

**Comment by pinkforest** [comment]
Drafted #433

**Comment by pinkforest** [comment]
If the digest is to be optional feature, here is a PR:
- #446

**Comment by pinkforest** [comment]
This was resolved in:
- https://github.com/dalek-cryptography/curve25519-dalek/pull/453

Can be closed
