### ISSUE TITLE
Scalar::bits

### ISSUE THREAD

**Issue by burdges** [dalek-cryptography/curve25519-dalek#448]
We're mildly worried about the [`Scalar::bits`](https://github.com/dalek-cryptography/curve25519-dalek/blob/main/src/scalar.rs#L825) method.  It's always used with another loop in https://github.com/dalek-cryptography/curve25519-dalek/blob/main/src/montgomery.rs#L319-L322 so maybe the compiler unifies the loops, and removes the intermediate 256 byte array, and maybe this even helps behind the scenes optimizations, but..

A priori it feels risky to do this, like did anyone check if the compiler leaves secret key material on the stack?   An iterator should unify the loops for sure.

**Comment by rozbb** [comment]
Resolved in #451
