### ISSUE TITLE
u32_backend is slower than u64_backend on armv7 Android

### ISSUE THREAD

**Issue by jrose-signal** [dalek-cryptography/curve25519-dalek#449]
I noticed the upcoming 4.0 release has removed the u32_backend and u64_backend features in favor of checking the target pointer size, which seems very sensible.* We know the u32_backend can be drastically faster than the u64_backend in some configurations:

> On my Xperia 10 with SailfishOS (armv7hl user space on aarch64 kernel, yes I know, rustflags = "-C target-feature=+v7,+neon"):
> - u32_backend + std: [644.25 us 646.59 us 649.28 us]
> - u64_backend + std: [6.4522 ms 6.4685 ms 6.4880 ms]

…but not all:

> On a Cortex-M3 (Texas Instruments CC2538):
> - u32_backend without alloc: 470507 cycles
> - u32_backend with alloc (wut): 878507 cycles
> - u64_backend without alloc: 494078 cycles
> - u64_backend with alloc: 470502 cycles (the fastest)

(https://github.com/signalapp/libsignal/issues/453#issuecomment-1068184262)

Today I finally got around to running some 32-bit microbenchmarks on a *new* Android phone (with help from a coworker), a Pixel 6a, which I feel should nonetheless still produce interesting results because, well, running armv7 code on an aarch64 device can't magically use 64-bit registers. We consistently found that the u32_backend was 5-15% *slower* than the u64_backend when compiling for that particular armv7.

_EDIT: Later, I tested on a 32-bit Moto X and got approximately the same results._

All of this is differences of at most a tenth of a millisecond on any particular operation (we tested key agreement and signing + verifying), so it's not like it's going to make or break the crate. But it did make me think twice about "u32_backend is for 32-bit CPUs, u64_backend is for 64-bit CPUs". Is that worth restoring feature flags to *override* the default inference?

\* Especially given that the previous config made it easy for a downstream crate to depend on u64_backend implicitly as a default feature, thus removing the chance for the final program to choose the u32_backend instead.

**Comment by jrose-signal** [comment]
Hypothesis about @rubdos' drastic Xperia results: the compiler is doing a terrible job vectorizing the u64 backend for armv7 (target feature `+neon`). We don't get that because some 32-bit Android phones really are that low-end.

**Comment by tarcieri** [comment]
> running armv7 code on an aarch64 device can't magically use 64-bit registers. We consistently found that the u32_backend was 5-15% slower than the u64_backend when compiling for that particular armv7.

To be clear: this is a 64-bit device, and you are worried about the performance of running a 32-bit binary on it? If so, why aren't you building a 64-bit binary?

Something else I've generally worried about is whether using the 64-bit backend on a 32-bit target impacts constant-time operation. I haven't done any investigation there, but I think it's worth looking into.

All that said, I think it would be good to have a way to override the selected backend for these particular cases, but using feature flags for this purpose runs afoul of some of the original problems #414 was meant to address, like: what happens if `u32_backend` and `u64_backend` are both enabled, or if `fiat_backend` or `simd_backend` are enabled as well.

It would probably be good to use a `cfg` attribute for this purpose, which also solves this problem:

> Especially given that the previous config made it easy for a downstream crate to depend on u64_backend implicitly as a default feature, thus removing the chance for the final program to choose the u32_backend instead.

Indeed it's a bit worse than that. If you have any dependencies that explicitly activate different backends it would result in a compile error with pages and pages of type errors.

Using a `cfg` attribute ensures only the toplevel binary can choose the backend, and using a `cfg` attribute like e.g. `dalek_backend` ensures only one backend can be explicitly selected.

**Comment by tarcieri** [comment]
Also note that if we do switch to `cfg` attributes, we could potentially ship v4.0 while punting on manual overrides for `u32_backend`/`u64_backend` as it would make the backend selection futureproof.

I think it will require some internal refactoring to implement cleanly, moving all of the relevant logic for selecting the backend to a single place so it doesn't need to be duplicated. Right now it's somewhat spread out.

**Comment by jrose-signal** [comment]
> To be clear: this is a 64-bit device, and you are worried about the performance of running a 32-bit binary on it? If so, why aren't you building a 64-bit binary?

Convenience only: Google's Microbenchmark framework doesn't work pre-Android-7, but all our 32-bit test devices are deliberately still on older versions of Android for testing. At some point I'll go find a third-party benchmarking library to test it properly.

I don't love the `cfg` thing; it does guarantee a single selection, but it loses discoverability, and if you misspell the feature you'll never know. I get that Cargo doesn't provide a perfect answer at the moment, though.

**Comment by tarcieri** [comment]
Yeah, unfortunately I've found no way to check that a given `cfg` value is within an allowed set without making it mandatory.

Likewise there's no way to ensure the right name is used for the `cfg` attribute.

That said, it's the only way to move control to the toplevel binary, rather than transitive dependencies, as well as the only way to ensure a single option is specified versus multiple potential (transitively) activated features like `u32_backend` and `u64_backend`.

**Comment by burdges** [comment]
Just fyi wasm needs 64 bit arithmetic but has 32 bit pointers, not sure if you made an exception for that and similar cases.  I suppose wasm likely needs other strange things anyways.

**Comment by jrose-signal** [comment]
> Convenience only: Google's Microbenchmark framework doesn't work pre-Android-7, but all our 32-bit test devices are deliberately still on older versions of Android for testing. At some point I'll go find a third-party benchmarking library to test it properly.

Just to circle back: I did a clunky benchmark using `System.nanoTime()` and a single warmup before many repeated invocations on an old 32-bit Moto X, and the results were about reliably the same as the 64-bit device: the 32-bit backend is 5-15% slower than the 64-bit backend.

**Comment by jrose-signal** [comment]
🤦 Also I typo'd the original report: the difference on both phones is a tenth of a *millisecond,* which is still pretty small but also 1000 times as big as a tenth of a *microsecond.*

**Comment by tarcieri** [comment]
Do you all think it would make sense to enable the 64-bit backend by-default on `target_arch = "arm"`? (along with WASM)

**Comment by rozbb** [comment]
So we would have auto-selection by default, with a `cfg` override? If so, that sounds reasonable to me. How difficult would it be to get an MVP of the cfg flag overrides working so we can include it in the 4.0 breaking changes?

**Comment by rubdos** [comment]
FWIW, we have a WIP neon-backend version in https://github.com/zkcrypto/curve25519-dalek-ng/pull/19 that I'm cleaning up and making armv7-compatible. Requires https://github.com/rust-lang/stdarch/pull/1363

I presume most ARMv7 phones will come with NEON, but @jrose-signal will probably know better.

**Comment by jrose-signal** [comment]
> I presume most ARMv7 phones will come with NEON, but @jrose-signal will probably know better.

Most do but some don't, so it would be dynamic selection / a code size tradeoff for us. Others might not care about low-end / older ARMv7 though.

**Comment by tarcieri** [comment]
FWIW we could add 32-bit ARM support for detecting `neon` to the `cpufeatures` crate, which works on `stable` Rust

**Comment by rubdos** [comment]
> FWIW we could add 32-bit ARM support for detecting `neon` to the `cpufeatures` crate, which works on `stable` Rust

Ack. If you're interested in a PR for the aarch64 version, we can prepare that already, that's already quite clean and tested. We'll need to wait for https://github.com/rust-lang/stdarch/pull/1363 anyway before our armv7 neon code would be up for consideration...

**Comment by tarcieri** [comment]
That'd be great. My understanding is on `aarch64` the `target_feature` for `neon` should always be enabled?

**Comment by rubdos** [comment]
> That'd be great. My understanding is on `aarch64` the `target_feature` for `neon` should always be enabled?

That's how I understood it too. @Tarinn and I still have to figure out some little patch we did today. To make stuff compatible with ARMv7, we switched from a table lookup to a `shuffle!` call in packed_simd, and we'd need to test which one is faster on aarch64. I'll do that tomorrow first thing and send a PR here. My understanding is that it might conflict a bit with #454, but we'll see how that pans out.

**Comment by pinkforest** [comment]
> My understanding is that it might conflict a bit with https://github.com/dalek-cryptography/curve25519-dalek/pull/454, but we'll see how that pans out.

After initial :woman_facepalming: I simplified that quite bit de-coupling from backend refs .. see how it will parachute-in now :sweat_smile:

**Comment by pinkforest** [comment]
Also if there is something to add to well known defaults over the `cfg(target_pointer_width)` lottery
 - https://github.com/dalek-cryptography/curve25519-dalek/issues/456
