### ISSUE TITLE
fiat backend MSRV is 1.57.0

### ISSUE THREAD

**Issue by pinkforest** [dalek-cryptography/curve25519-dalek#462]
When testing `cfg(curve25519_dalek_serial)` addressing #437 

foobar@foobar-MS-7C77:~/cc/curve25519-dalek$ env RUSTFLAGS="--cfg curve25519_dalek_serial=\"fiat\"" cargo test
```
error: package `os_str_bytes v6.4.1` cannot be built because it requires rustc 1.57.0 or newer, while the currently active rustc version is 1.56.1
```

**Comment by tarcieri** [comment]
That appears to be unrelated to [`fiat-crypto` which has no dependencies](https://crates.io/crates/fiat-crypto/0.1.17/dependencies)

For starters, `--cfg curve25519_dalek_serial="fiat"` is not the correct name for the `cfg` directive (and this is a good example of a downside of using `cfg`, namely we get no checks for invalid `cfg` attributes). It should be `curve25519_dalek_backend="fiat"`.

`os_str_bytes` is being pulled in as:

`dev-dependencies` -> `criterion` -> `clap` v3 -> `clap_lex` -> `os_str_bytes`

...so this should only affect the MSRV when running `cargo test`, not the MSRV of the overall crate.

We also use `-Z minimal-versions` to test MSRV.

**Comment by pinkforest** [comment]
Ah that makes sense, closing.

**Comment by pinkforest** [comment]
How can we spit out` -Z minimal-versions` to CI btw as that is hardcoded there atm ?
I mean how could we select the toolchain automatically based on that.

**Comment by pinkforest** [comment]
nvm we have it in CI!

**Comment by tarcieri** [comment]
These parts of the job:

```
 - uses: dtolnay/rust-toolchain@1.56.1
 - run: cargo build --no-default-features --features serde
```

...check that it builds successfully with 1.56.1, the advertised MSRV.

**Comment by pinkforest** [comment]
yes - _build_ yes but not _test_ :)

**Comment by tarcieri** [comment]
Aah, yeah it should probably test MSRV.

That’s easy enough to do by adding MSRV and stable to the `test` matrix.
