### ISSUE TITLE
`simd_backend` with `fiat_u64::FieldElement51`

### ISSUE THREAD

**Issue by pinkforest** [dalek-cryptography/curve25519-dalek#464]
In #463 

When testing simd_backend with fiat serial there is either a flaky test or `fiat_u64::FieldElement51`

Repro - pull https://github.com/dalek-cryptography/curve25519-dalek/pull/463 and:
$ env RUSTFLAGS="--cfg curve25519_dalek_backend=\"simd\" --cfg curve25519_dalek_serial=\"fiat\" -C target_feature=+avx2" cargo +nightly test
```
---- backend::vector::avx2::field::test::diff_sum_vs_serial stdout ----
thread 'backend::vector::avx2::field::test::diff_sum_vs_serial' panicked at 'assertion failed: `(left == right)`
  left: `FieldElement51([4503599627370558, 4503599627370594, 4503599627370594, 4503599627370594, 4503599627370594])`,
 right: `FieldElement51([100, 100, 100, 100, 100])`', src/backend/vector/avx2/field.rs:917:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    backend::vector::avx2::field::test::diff_sum_vs_serial
```

**Comment by tarcieri** [comment]
Ugh, that almost looks like miscompilation

**Comment by pinkforest** [comment]
Yeah and I should not have tried that what caused this so closing this :)
