### ISSUE TITLE
Should the tables be static instead of const?

### ISSUE THREAD

**Issue by elichai** [dalek-cryptography/curve25519-dalek#486]
I wonder if the fact that the generator tables are const could result in the table replicating across compilation units and if it should be a static instead.

I did not check binaries for this nor did I dive into how by-reference const access happens in rust

**Comment by tarcieri** [comment]
It seems like all the accesses borrow the basepoint table, e.g.

```rust
let bp = &constants::ED25519_BASEPOINT_TABLE * &Scalar::ONE;
```

Perhaps it should just be declared as a `'static` reference to begin with?

```rust
pub const ED25519_BASEPOINT_TABLE: &'static EdwardsBasepointTable = ...
```

I'm not sure if that alone is sufficient to prevent duplicating the table, does it still need to be declared `static` too?

```rust
pub static ED25519_BASEPOINT_TABLE: &'static EdwardsBasepointTable = ...
```

**Comment by elichai** [comment]
@tarcieri 
AFAIR `const A: &'static Something = &...` compiles to:
```
static _anonymous_A: Something = ...;
const A: &'static Something = &_anonymous_A;
```
