### ISSUE TITLE
Build script failure on platform detection

### ISSUE THREAD

**Issue by semenov-vladyslav** [dalek-cryptography/curve25519-dalek#508]
Automatic backend (`DalekBits`) detection in curve25519-dalek-4.0.0-rc.1 `build.rs` fails at unwrap `platforms::Platform::find(&target_triplet).unwrap()` while building a risc0 guest method using ed25519-dalek crate. The actual `target_triplet` is `riscv32im-risc0-zkvm-elf`. I was unable to configure `curve25519_dalek_bits` externally, risc0-build doesn't allow it yet, and `.cargo/config` didn't work either. As a workaround we could return `DalekBits::Dalek32` if the platform is not found since this is the default value returned for weird `target_pointer_width`.

**Comment by pinkforest** [comment]
Wait a sec this shouldn't happen if you used curve25519_dalek_bits = 32 | 64

```
    #[cfg(all(not(curve25519_dalek_bits = "64"), not(curve25519_dalek_bits = "32")))]
    let curve25519_dalek_bits = lotto_curve25519_dalek_bits();
```

How did you configure `durve25519_dalek_bits` as this code point would not trigger given the above ?

You cannot control the `cfg()` from transient dependency - see https://github.com/pinkforest/cfg_lottery_demo

**Comment by semenov-vladyslav** [comment]
#510 didn't actually fix the issue. Now I get:

```
Error: Unknown Rust target platform.
Please set cfg(curve25519_dalek_bits) explicitly either as 32 or 64.
```

But I had this issue because I couldn't set `curve25519_dalek_bits` in the first place.

**Comment by pinkforest** [comment]
It fixed the correct issue -

The build here is using a custom target which does not signal cfg to rustc which is the problem here.

Could please share the details how it is being built exactly e.g. which commands with cargo I assume ?

**Comment by tarcieri** [comment]
@semenov-vladyslav can you not set the `RUSTFLAGS` environment variable?

**Comment by pinkforest** [comment]
Raised a follow-up issue: #41 

But would be good to know more details re: build command e.g. `RUSTENV` which rustc uses to set the `cfg` flag.

`env RUSTFLAGS='--cfg curve25519_dalek_bits="32"' <build command>` should work with rustc unless the custom build command that does exec() on rustc doesn't pass it on ?
