### ISSUE TITLE
Default `curve25519_dalek_bits` on non-standard Rust target / build tooling

### ISSUE THREAD

**Issue by pinkforest** [dalek-cryptography/curve25519-dalek#511]
**Follow-up**

- #508 and
- #510 

**Use-Case**

- **a)** Non-standard Rust build tooling which doesn't signal `cfg` correctly and

- **b)** Custom non-Rust targets which are not known or

- **c)** Situations where the `RUSTENV` was set incorrectly but relied on

**Current**

We spit out an error https://github.com/dalek-cryptography/curve25519-dalek/issues/508#issuecomment-1465049852 where we ask the downstream to set the desired `cfg(curve25519_dalek_bits)`

This ensures that the downstream is consciously selecting the correct `curve25519_dalek_bits` if the downstream is attempting to use the `cfg` to set it and errors out appropriately when the target platform is non-standard Rust target with unknown `target_pointer_width`

**Alternative**

Set the `cfg(curve25519_dalek_bits)` to `32` silently if either the `cfg` was not signalled or a custom non-standard Rust target.

This would have a downside where it would silently set something else but it would "just work" on other hand but silently.

**Potential Improvements**

1) Maybe we could print out a warning ? Do people read warnings ?

2) Also maybe could add some tests that simulate these error messages.

3) Document these error messages in README

**Comment by pinkforest** [comment]
It seems some of these are using a Makefile where simple thing is just to add the environment variable in there.

e.g. this is just a matter of education given we've changed this - educational blog coming up I think will suffice here.

Will just add some woridng around Makefile

**Comment by tarcieri** [comment]
I think picking some default and if possible printing a warning is the way to go.

It seems enough people have hit this even in prerelease testing we should do something about it.

**Comment by pinkforest** [comment]
I suspect this may be a cargo / rustc bug - I have a feeling it doesn't allow passing cfg with custom targets.

**Comment by pinkforest** [comment]
So if we introduce the environment variables for build:

curve25519_dalek_bits  and
curve25519_dalek_backend

This would work/around the rustc issue not setting `cfg` correctly and allows people set these.

Even if we hack a default for bits then people would be having problems setting these that is an issue as well we need to address.

**Comment by jcape** [comment]
Is there an advantage to using these new variables vs. the `CARGO_CFG` variable which @ryankurte suggested?

**Comment by pinkforest** [comment]
Does it relay the `CARGO_CFG` correctly considering the derive cfg-predicates didn't work unlike in standard targets ?

**Comment by pinkforest** [comment]
@jcape the PR is up #516 with @ryankurte fix - as indeed that variable works across all the rust versions we support and various configurations.

Given the complexity of setting these cfg flags we might just fallback to u32 and print out that warning.

**Comment by pinkforest** [comment]
I just checked that there seems to be no way of doing "warnings" in build scripts :woman_shrugging: 

So it's either hard error or transparently set something the end-user might not have intended to be set.

**Comment by jcape** [comment]
FWIW, you can use `println!("cargo:warning=the string");`, or https://docs.rs/cargo-emit/latest/cargo_emit/macro.warning.html

**Comment by pinkforest** [comment]
Ah thanks! Think we'll just default to `Dalek32` and put that one out then.

**Comment by pinkforest** [comment]
PR is up:
- https://github.com/dalek-cryptography/curve25519-dalek/pull/516
