### ISSUE TITLE
4.0.0 Remaining Breaking Changes

### ISSUE THREAD

**Issue by pinkforest** [dalek-cryptography/curve25519-dalek#521]
This issue is referred from rc.2 README

**Scalar API**
- https://github.com/dalek-cryptography/curve25519-dalek/issues/514
- https://github.com/dalek-cryptography/curve25519-dalek/issues/507
- https://github.com/dalek-cryptography/curve25519-dalek/pull/519

Scalar API can be either rc.3 OR 4.1.0 SemVer exempted or gated via feature.

However does not stop us releasing rc.2 and get the usage from 10% to get more usage across the crates.

**Comment by tarcieri** [comment]
A plan for #380 would also be good

**Comment by tarcieri** [comment]
I posted a non-breaking plan for #380 here: https://github.com/dalek-cryptography/curve25519-dalek/issues/380#issuecomment-1567527591

That said, I think all of these are done.
