### ISSUE TITLE
CPU auto-detection feature / cfg gate

### ISSUE THREAD

**Issue by pinkforest** [dalek-cryptography/curve25519-dalek#529]
This should not block landing #523 and can be done as follow-up

Follow-up from 
- https://github.com/dalek-cryptography/curve25519-dalek/pull/523#issuecomment-1572521178

Cc/ @jrose-signal @koute

**Comment by pinkforest** [comment]
Some q's

1) Which use-cases would need to disable the CPU detecion ? Or is this just in case something goes wrong a.k.a "break glass" ?

2) Is there much use for disabling CPU detection or should there be just plain override vs disallowing detection ?

3) Should we just re-use `cfg(curve25519_dalek_backend)` "override" which could be `simd` | `simd_avx512` | `simd_avx2`

4) We already use some hazardous / risky features that should be enabled with care and not sure how many use `--all-features`

Having a plain override with `cfg()` would align to everything else we've done - it would be great to know what use-cases there are to make it easier if it's widely expected to be used ?

**Comment by tarcieri** [comment]
I would think that specifying `curve25519_dalek_backend` would override autodetection

**Comment by tarcieri** [comment]
> If there's ever autodetection for mobile platforms, we might want to turn it off if it's not enough of a speedup to be worth the extra code.

I would think mobile platforms are ARM64, in which case the `neon` target feature is enabled by default (#457)

**Comment by pinkforest** [comment]
Yeah consensus here seems to be that override seems to be the best.

There is this discussion re-opened so let's redirect there to simplify things further:
- https://github.com/dalek-cryptography/curve25519-dalek/issues/414

**Comment by tarcieri** [comment]
Oh sorry, I forgot you opened this issue, but thanks for directing the conversation back to #414

**Comment by pinkforest** [comment]
Yeah I think we got consensus on this issue so your get-together words it well what needs ot happen overall :)
