### ISSUE TITLE
Update zeroize package.

### ISSUE THREAD

**Issue by Zedonboy** [dalek-cryptography/curve25519-dalek#534]
Hello, i am having issue with this package because the zeroize package is outdated, therefore there's a conflict.

Would you please change to the latest version.

Thanks

**Comment by tarcieri** [comment]
Try the latest rc: https://crates.io/crates/curve25519-dalek/4.0.0-rc.2

**Comment by Zedonboy** [comment]
4.0.0 is not compatible with solana-sdk.

I was told i have to wait. Until a major release.

**Comment by tarcieri** [comment]
Ok, it should be out soon
