### ISSUE TITLE
missing author info and license files for curve25519-dalek-derive

### ISSUE THREAD

**Issue by alexanderkjall** [dalek-cryptography/curve25519-dalek#589]
The readme file refers to license files that gives 404's here:

https://github.com/dalek-cryptography/curve25519-dalek/blob/main/curve25519-dalek-derive/README.md?plain=1#L189

Could I assume that the authors are the same as curve25519-dalek when packaging this for Debian?

**Comment by rozbb** [comment]
Good catch. I think it would be the people who contributed the crate. I'll make that PR and clarify things

**Comment by rozbb** [comment]
Update: the license files will be moved into the repo in https://github.com/dalek-cryptography/curve25519-dalek/pull/590

**Comment by rozbb** [comment]
Merged that PR. License files are now there. They don't have any copyright lines bc the author waived it. Feel free to reopen if this doesn't answer your question

**Comment by tarcieri** [comment]
Perhaps we should cut another crate release that includes these files?

**Comment by tarcieri** [comment]
Yes, that's fine

**Comment by rozbb** [comment]
How necessary is it to name a specific person? It [seems](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#copyright-field) like the field is freeform. So would `Copyright 2023` work? I say this because I don't want to misrepresent the origin of the file, and placing "RustCrypto Developers" after a nonexistent copyright line is indistinguishable from claiming the whole thing was made by RustCrypto developers

**Comment by tarcieri** [comment]
You could say "Dalek Developers"

**Comment by alexanderkjall** [comment]
So copyright isn't about who created a piece of work, it rather about documenting who owns the copyright of the thing.

The reason I ask is that I don't fully understand what it means to "waive" ones copyright, I presumed it meant that they transferred their copyright to someone else, maybe to the group of developers who have built these crates, aka the RustCrypto Developers.

In a hypothetical scenario: If there was a pressing need to relicense this work under another license, who could do that?

**Comment by tarcieri** [comment]
@koute is the principal author of `curve25519-dalek-derive`
