### ISSUE TITLE
Pointer width detection in `build.rs`  may break for obscure platforms

### ISSUE THREAD

**Issue by Shnatsel** [dalek-cryptography/curve25519-dalek#610]
[The build.rs file](https://github.com/dalek-cryptography/curve25519-dalek/blob/main/curve25519-dalek/build.rs) currently uses the `platforms` crate to map the rustc target triples to pointer width. I am the author of the `platforms` crate :wave: 

The `platforms` crate adds and removes targets following the target support in the latest release of rustc. This means that the list of targets it knows about may be different from the list of targets that your local `rustc` knows about.

It would be better to query the Rust compiler directly instead of relying on the `platforms` crate. You can do it with `rustc --print=cfg --target=TRIPLE`, e.g. `rustc --print=cfg --target x86_64-unknown-uefi` will print the pointer width, among other things. By sourcing it from the compiler that performs the build, there is no chance of the pointer width data to be missing.

**Comment by pinkforest** [comment]
Thanks - Yeah thought about that but `platforms` was just ergonomic at the time.

I also thought we could expand to `rustc-metadata` but then there was already [rustc-cfg](https://crates.io/crates/rustc-cfg) which we could add and could be suited for the task either with modifications or directly.

But [we've used environment variables](https://github.com/dalek-cryptography/curve25519-dalek/blob/main/curve25519-dalek/build.rs#L39C44-L39C61) for this which even `rustc-cfg` recommends over that create - also saving dep as a bonus.

So I guess we can just read the environment variable `CARGO_CFG_TARGET_POINTER_WIDTH` instead and drop the dep indeed despite it being slightly ergonomic and giving better idea about obscure platforms as you've noted :+1:
