### ISSUE TITLE
ed25519_dalek No generate function

### ISSUE THREAD

**Issue by programskillforverification** [dalek-cryptography/curve25519-dalek#614]
I am trying to run code provided in document.

![1](https://github.com/dalek-cryptography/curve25519-dalek/assets/65984904/5fcab1b8-312a-448b-a71b-4f6fd44ffa48)

The compiler tell me:

let signing_key: SigningKey = SigningKey::generate(&mut csprng);
  |                                               ^^^^^^^^ function or associated item not found in `SigningKey`

This is my dependencies
[dependencies]
ed25519-dalek = "2.1.0"
rand = "0.8.5"

**Comment by robjtede** [comment]
As [documented](https://docs.rs/ed25519-dalek/latest/ed25519_dalek/struct.SigningKey.html#method.generate) feature is required:

```toml
ed25519-dalek = { version = "...", features = ["rand_core" } 
```

**Comment by programskillforverification** [comment]
> As [documented](https://docs.rs/ed25519-dalek/latest/ed25519_dalek/struct.SigningKey.html#method.generate), a crate feature is required:
> 
> ```toml
> ed25519-dalek = { version = "...", features = ["rand_core"] } 
> ```

Thanks a lot!
