### ISSUE TITLE
[docs request] how to serialize a public key in the format compatible with `~/.ssh/authorized_keys`?

### ISSUE THREAD

**Issue by samuela** [dalek-cryptography/curve25519-dalek#634]
I'm attempting to more-or-less replicate the functionality of ssh-keygen with ed25519-dalek. I have poked around quite a bit but have not yet succeeding in generating a serialization of a public key that matches the format standard in `~/.ssh/authorized_keys`: `AAAAC3NzaC1lZDI1NTE5AAAA<xxxxxxxxxxxxx>`.

Peeking at https://gist.github.com/thwarted/1024558 it looks like some DER serialization is necessary, but I have not yet found success generating a key that matches the expected format.

How does one accomplish this?

**Comment by tarcieri** [comment]
You can use the @RustCrypto `ssh-key` crate, which has a first-class integration with `ed25519-dalek`.

Specifically you might be interested in the [`ssh_key::PublicKey`](https://docs.rs/ssh-key/latest/ssh_key/public/struct.PublicKey.html) type. You can [convert from `ed25519_dalek::VerifyingKey` using this `From` impl](https://docs.rs/ssh-key/latest/ssh_key/public/struct.Ed25519PublicKey.html#impl-From%3C%26VerifyingKey%3E-for-Ed25519PublicKey).

See also [`ssh_key::authorized_keys`](https://docs.rs/ssh-key/latest/ssh_key/authorized_keys/index.html).

**Comment by samuela** [comment]
Awesome sauce, thanks @tarcieri !
