### ISSUE TITLE
Zeroize `SecretKey` on drop

### ISSUE THREAD

**Issue by dmitry-markin** [dalek-cryptography/curve25519-dalek#650]
`SecretKey` is currently a type alias for `[u8; SECRET_KEY_LENGTH]`, which doesn't get zeroed when dropped. This issue is about zeroizing the key data when dropping.

This was the case before https://github.com/dalek-cryptography/curve25519-dalek/commit/52da7353b816152f2009a45bdead77cb26036f69, when `SecretKey` was a struct implementing zeroize on `Drop`.

**Comment by tarcieri** [comment]
We can’t add trait impls for `[u8; 32]`: it’s just a byte array.

If you want it zeroized, you’ll need to do it yourself. There’s literally nothing this library can do.

**Comment by dmitry-markin** [comment]
What about using a dedicated type for `SecretKey`? As users can misuse an array forgetting to zeroize it.

**Comment by tarcieri** [comment]
And where do you get the bytes to make that `SecretKey`, and how do you ensure those are zeroed? At some point some bytes come into the library externally to what it can manage.

The main way `SecretKey` is used is as a `&SecretKey` reference here: https://docs.rs/ed25519-dalek/latest/ed25519_dalek/struct.SigningKey.html#method.from_bytes

Adding a `SecretKey` newtype would force those bytes to be copied from somewhere else, just so it could manage zeroing them. So it would actually result in an additional copy of the secret being made, which is strictly worse.

**Comment by dmitry-markin** [comment]
Makes sense, thanks for the explanation. I was looking at [`SecretKey::try_from_bytes`](https://github.com/libp2p/rust-libp2p/blob/0340c5236eea2e847e7c3011fc5364118748ee46/identity/src/ed25519.rs#L194) in `libp2p` that takes mutable reference and zeroes the user provided data after conversion, and though it might be a good idea for library to take care of destroying sensitive data.

**Comment by tarcieri** [comment]
Key data needs to be frequently decoded from inout sources that can’t easily provide mutable references like key file formats (e.g. PKCS#8, OpenSSH)
