### ISSUE TITLE
4.1.3 release?

### ISSUE THREAD

**Issue by jrose-signal** [dalek-cryptography/curve25519-dalek#655]
As you know, Signal has a fork of curve25519-dalek (to add bidirectional Elligator mapping to and from RistrettoPoints, discussed in #533). We'd like to pull in the latest tag, but 4.1.2 no longer passes its own CI, because of new warnings and such on nightly. We could pull in the fixes on main as well, but then we're between official releases. It's not a *huge* deal, but is there a 4.1.3 coming soon?

**Comment by jrose-signal** [comment]
Ping, looks like there haven't been any changes in the last month besides the license normalization anyway!

**Comment by tarcieri** [comment]
We'll be cutting a release soon

**Comment by tarcieri** [comment]
Closed by #660 (which includes a security fix, so please upgrade!)
