### ISSUE TITLE
Add the ability to convert `[u8; 32]` into a `VerifyingKey`

### ISSUE THREAD

**Issue by zacknewman** [dalek-cryptography/curve25519-dalek#674]
Currently there is no way to directly convert `[u8; 32]` into a [`VerifyingKey`](https://docs.rs/ed25519-dalek/latest/ed25519_dalek/struct.VerifyingKey.html). I propose adding a `TryFrom<[u8; 32]>` implementation and a corresponding `from_array` function. This would not only add symmetry since one can already convert to an array via [`VerifyingKey::to_bytes`](https://docs.rs/ed25519-dalek/latest/ed25519_dalek/struct.VerifyingKey.html#method.to_bytes), but it will also allow one to explicitly copy the array instead of the implicit copy that occurs in [`VerifyingKey::from_bytes`](https://docs.rs/ed25519-dalek/latest/ed25519_dalek/struct.VerifyingKey.html#method.from_bytes).

`VerifyingKey::from_bytes` can then be re-written to just redirect to this array conversion instead.

**Comment by tarcieri** [comment]
See the existing `VerifyingKey::from_bytes` method: https://docs.rs/ed25519-dalek/latest/ed25519_dalek/struct.VerifyingKey.html#method.from_bytes

There's also an existing impl of `TryFrom<&[u8]>`. Since point decompression is fallible anyway, a separate `TryFrom<&[u8; 32]>` adds little value, especially since `[u8; 32]` will deref to `&[u8]`.

**Comment by tarcieri** [comment]
There is no advantage to an owned API over borrowing, only disadvantages.

**Comment by tarcieri** [comment]
32-bytes is *significantly* larger than a 64-bit pointer, which is the threshold at which borrowing becomes advantageous over a copy.

Regardless, it makes no sense to support both owned and borrowed APIs here. Just borrow and use the existing APIs.

**Comment by tarcieri** [comment]
Because the caller can potentially make use of an owned result. These constructors can’t.

**Comment by tarcieri** [comment]
You’re talking about a value that’s twice the size of a pointer, versus four times. And that’s for consistency with the other methods that are pointer size or smaller.

And they don’t offer *both options*, they chose the single option that made the most sense for their use case, as have we.

**Comment by tarcieri** [comment]
We’re not going to be making any breaking changes any time soon. There is ample previous discussion of that function’s signature I can link you when I’m not on a phone.

**Comment by tarcieri** [comment]
See #491, and no it’s not more consistent, `Scalar::from_bytes_mod_order` is the only API that accepts an owned argument. There is no point to adding duplicate APIs just to save you typing `&`.

**Comment by tarcieri** [comment]
This discussion isn’t going anywhere productive. Please review #491.
