### ISSUE TITLE
Experimental supports cfg

### ISSUE THREAD

**Issue by pinkforest** [dalek-cryptography/curve25519-dalek#694]
Re:
- https://github.com/dalek-cryptography/curve25519-dalek/issues/635
- https://github.com/dalek-cryptography/curve25519-dalek/issues/693

p.s. how do we implement the opt-in given we have declared backend details as implementation detail.

feature will not do as it poses problems of a) relaying across dependency chain b) not having top-level binary in control

Same as #414 we could use cfg for this - I  propose:

`cfg(curve25519_dalek_unstable = "avx512")`

Which will in turn support for unstable AVX512 through nightly opt-in unstables basis.

**Comment by tarcieri** [comment]
I would suggest using the existing `curve25519_dalek_backend`cfg rather than adding yet another one

**Comment by pinkforest** [comment]
Problem is this is more like sub-configuration and it conflates configuration between stable and unstable configuration.

By denoting explicitly that it's experiment it avoids the confusion of opting into something that is not entirely stable.

**Comment by tarcieri** [comment]
Having two different cfg options for the backend reintroduces the problem that they can both be set in conflicting states, which was the whole reason we moved away from features in the first place.

I think we already have all the cfg options we need and the main thing we need to do at this point is *not* automatically enable nightly-only features.

**Comment by pinkforest** [comment]
The cfg conflict happens even today, it is perfectly possible to set two cfg options on same key -

However we guard and test that in build script just like we would guard the opt-in which is different to override.

**Comment by tarcieri** [comment]
Your example would be caught by the compiler, as opposed to requiring logic at every backend selection site.

I very strongly believe we should not (re)introduce backend selection knobs that duplicate/conflict with each other.

**Comment by pinkforest** [comment]
The current backend knobs are overrides and it does not guarantee selection though.

We can settle with `backend="unstable_avx512"` and at least the value denotes the override into unstable sub-backend.

**Comment by tarcieri** [comment]
Regardless, the point is not to have logic in backend selection code all over the place that has to handle potentially conflicting user inputs.

That would be a major regression over where we are now.

**Comment by pinkforest** [comment]
Can you comment on having the unstable_ in the value to denote it's unstable-ness?

**Comment by tarcieri** [comment]
That seems better than two potentially conflicting attributes

**Comment by pinkforest** [comment]
Cool great let's do that
