### ISSUE TITLE
signing_key.sign_prehashed ... method not found in SigningKey

### ISSUE THREAD

**Issue by diudiudiuu** [dalek-cryptography/curve25519-dalek#700]
### code
```
use ed25519_dalek::SigningKey;
use ed25519_dalek::Signature;
use sha2::{Sha512, Digest};
use hex_literal::hex;


pub fn sign(message: &str) -> String {
    
    let sec_bytes = hex!("b23dfd4a2ca755e6ddccfcaa31201d1f6ec7fe0290086d53b931e0cd1a6f80fd");
    let signing_key = SigningKey::from_bytes(&sec_bytes);

    let mut prehash_for_signing = Sha512::default();
    prehash_for_signing.update(message.as_bytes());

    let signature: Signature = signing_key.sign_prehashed(prehash_for_signing, None).unwrap();
    hex::encode(signature.to_bytes())
}
```
### version 
ed25519-dalek = "2.1.1"
hex = "0.4.3"
hex-literal = "0.4.1"
sha2 = "0.10.8"

### image
![image](https://github.com/user-attachments/assets/4cc03255-9ca6-4d9a-a604-7913fb38e475)

**Comment by raphaelahrens** [comment]
You need the crate feature `digest`. (see https://docs.rs/ed25519-dalek/latest/ed25519_dalek/struct.SigningKey.html#method.sign_prehashed)

```
ed25519-dalek = { version = "$VERSION", features = [...,"digest"] }
```

**Comment by diudiudiuu** [comment]
> You need the crate feature `digest`. (see https://docs.rs/ed25519-dalek/latest/ed25519_dalek/struct.SigningKey.html#method.sign_prehashed)
> 
> ```
> ed25519-dalek = { version = "$VERSION", features = [...,"digest"] }
> ```

3Q
