### ISSUE TITLE
Looking for explanation for how to validate verifying key

### ISSUE THREAD

**Issue by TheButlah** [dalek-cryptography/curve25519-dalek#702]
The docs for [VerifyingKey::from_bytes](https://docs.rs/ed25519-dalek/latest/ed25519_dalek/struct.VerifyingKey.html#method.from_bytes) say that:

> Warning
>
> The caller is responsible for ensuring that the bytes passed into this method actually represent a curve25519_dalek::curve::CompressedEdwardsY and that said compressed point is actually a point on the curve.

I wanted to know if this verification is performed as part of [VerifyingKey::verify_strict](https://docs.rs/ed25519-dalek/latest/ed25519_dalek/struct.VerifyingKey.html#method.verify_strict) or if I still have to verify it myself.

If I need to verify it myself, would you accept a PR to add that to some example code.

Here is what I have so far, does it look correct?

```rust
#[derive(thiserror::Error, Debug)]
pub enum TryFromBytesError {
	#[error(
		"the provided bytes was not the y coordinate of a valid point on the curve"
	)]
	NotOnCurve,
	#[error("public key has a low order and is too weak, which would allow the key to generate signatures that work for almost any message. To prevent this, we reject weak keys.")]
	WeakKey,
}

// Instantiates `PubKey` from some bytes. Performs all necessary validation
/// that the key is valid and of sufficient strength.
///
/// Note that we will reject any keys that are too weak (aka low order).
pub fn try_from_bytes(bytes: &[u8; Self::LEN]) -> Result<VerifyingKey, TryFromBytesError> {
	let compressed_edwards = CompressedEdwardsY(bytes.to_owned());
	let Some(edwards) = compressed_edwards.decompress() else {
		return Err(TryFromBytesError::NotOnCurve);
	};
	let key = ed25519_dalek::VerifyingKey::from(edwards);
	if key.is_weak() {
		return Err(TryFromBytesError::WeakKey);
	}
	Ok(key)
}
```

**Comment by tarcieri** [comment]
We've discussed this in the past in #380 (and #626).

`VerifyingKey::from_bytes` decompresses a `CompressedEdwardsY`, and in performing point decompression it ensures the result is a valid curve point, or returns an error. So that warning is just out-of-date and should probably be removed.

In its place we should probably mention the current point validation criteria used: the ZIP-215 rules, as opposed to RFC8032 / NIST (see #626).

**Comment by tarcieri** [comment]
Opened #704 to update the wording

**Comment by TheButlah** [comment]
So to confirm- I don't need to mess with key validation at all myself, and can just use from_bytes?

**Comment by tarcieri** [comment]
Correct. Check the docs in #704 and let me know if they make sense now.
