### ISSUE TITLE
Conversion from Json Web Keys.

### ISSUE THREAD

**Issue by TheButlah** [dalek-cryptography/curve25519-dalek#703]
Hi, would you accept a PR to implement conversion from a Json Web Key to dalek's VerifyingKey? I would use the jose_jwk crate from the RustCrypto group.

Alternatively if supporting JWK is out of scope, would you accept a PR to add an example for this, with accompanying tests?

**Comment by tarcieri** [comment]
Note: the `jose-jwk` crate pulls in cryptographic crates as dependencies, not the other way around.

We'd be happy to have you add support, but it should go in `jose-jwk`, not here
