### ISSUE TITLE
Implement Elligator 2 (hashing to a curve point)

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/curve25519-dalek#8]
Stub issue for tracking Elligator 2 implementation.

**Comment by hdevalence** [comment]
Closing this for now, we can reopen it later if need be.

**Comment by isislovecruft** [comment]
Do we want to potentially add an invertible Elligator2 variant? It's rare that this is needed in practice, but there are systems like https://eprint.iacr.org/2019/1416 (cf. §4.1) which require not only _hash_-to-group but also _encode_-to-group (and the corresponding _decode_-to-group).

**Comment by hdevalence** [comment]
Hmm, I think that that's pretty different functionality from what this issue was about, so I'd prefer to discuss it separately from this issue.

**Comment by hdevalence** [comment]
For reference, it's possible to implement encode-to-group using the existing API without any changes to the library.  I wrote an example of how to do this last year: https://github.com/hdevalence/ristretto255-data-encoding/blob/master/src/main.rs

**Comment by isislovecruft** [comment]
Thanks! I'll open a separate issue for discussion.
