### ISSUE TITLE
Implement the remaining functionality needed for (V)XEdDSA

### ISSUE THREAD

**Issue by isislovecruft** [dalek-cryptography/curve25519-dalek#9]
Specifically, the functionality here which we don't already have: https://github.com/WhisperSystems/curve25519-java/tree/master/android/jni/ed25519/additions

I'd prefer to do this all at once (as in, all in one minor version), show it to Trevor, and then (if he approves) merge it in, rather than implement incrementally over time.

**Comment by isislovecruft** [comment]
What we have and don't have:

* `compare.c`
   - ✓ `crypto_verify_32_ref()` → `curve25519_dalek::util::arrays_equal_ct()`

* `curve_sigs.c`
   - ✓ `curve25519_sign()` → `ed25519_dalek::SecretKey::sign()`
   - ✓ `curve25519_verify()` → `ed25519_dalek::PublicKey::verify()`
   - However, both curve25519-java functions operate on curve25519 keys, so **we still need Mongomery x-coordinate → Edwards y-coordinate conversion.**

* `elligator.c`
   - `legendre_is_nonsquare()`
   - `elligator()`
   - `hash_to_point()`
   - `calculate_Bv()`
   - `calculate_Bv_and_V()`

* `fe_isequal.c`
   - ✓* `fe_isequal(f, g)` → `impl PartialEq for FieldElement`… *but* our implementation converts both `f` and `g` to a "canonical"/unique compressed representation first, and then compares byte-for-byte. I personally feel that a function which, in constant time, tests for equality of field elements (which may have different representations due to internal shifting in radix/carries) is *less* strict and *differently* expensive than one which does a representational conversion and tests byte-for-byte equality. However, I'm not sure how to best represent these two concepts clearly and usably in the API. Suggestions/ideas welcome. (* What I mean is "meh, ✓, this is kind of done but should have some further evaluation/discussion")

* `fe_mont_rhs.c`
   - `fe_mont_rhs()`

* `fe_montx_to_edy.c`
   - `fe_montx_to_edy()`

* `fe_sqrt.c`
   - `fe_sqrt()`

* `ge_isneutral.c`
   - `ge_isneutral()` **Note:** we do *not* want to test that a group element is equal to the identity in the way this function is doing so. This function is doing `(fe_isequal(p->X, zero) & fe_isequal(p->Y, p->Z))`… the latter part of that test allows `Y` and `Z` coordinates to be different to those of the identity element.

* `ge_is_small_order.c`
   - `ge_is_small_order()`

* `ge_montx_to_p2.c`
   - `ge_montx_to_p2()` **Note:** contains useful postcondition to check that (x,y) satisfies the curve equation, should probably be separate function.

* `ge_montx_to_p3.c`
   - `ge_montx_to_p3() **Note:** contains useful postcondition to check that (x,y) satisfies the curve equation, should probably be separate function.

* `ge_neg.c`
   - ✓ `ge_neg()` → `impl<'a> Neg for &'a ExtendedPoint`, etc.

* `ge_p3_to_montx.c`
   - ✓ `ge_p3_to_montx` We might have this in `decompress_montgomery()` in @hdevalence's `montgomery-x-format` branch.

* `ge_scalarmult.c`
   - ✓ `ge_scalarmult()` → `curve25519_dalek::ExtendedPoint.scalar_mult()`

* `ge_scalarmult_cofactor.c`
   - `ge_scalarmult_cofactor()`

* `keygen.c`
   - `curve25519_keygen()` **Note:** We used to have this in some of my old code before the release and we should probably just reanimate that corpse.

* `open_modified.c`
   - ✓ `crypto_sign_open_modified()` → `ed25519_dalek::PublicKey.verify()`

* `sc_clamp.c`
   - `sc_clamp()` This just does the standard curve25519 masking of key bits.

* `sc_cmov.c`
   - `sc_cmov()` We don't have `conditional_assign()` for scalars. We maybe should separate the `CTAssignable` trait into its own file?

* `sc_neg.c`
   - `sc_neg()`

* `sign_modified.c`
   - `crypto_sign_modified()` A much more sane EdDSA signing function, e.g. hash domain separations and better nonce derivation.

* `uopen_modified.c`
   - `crypto_usign_open_modified()`

* `usign_modified.c`
   - `crypto_usign_modified()`

* `utility.c`
   - ✓ `print_vector()` → `impl Debug for Vec<T>`
   - ✓ `print_bytes()` → `impl Debug for [u8]`
   - ✓ `print_fe()` → `impl Debug for FieldElement`

* `{u,v}xeddsa.c` **Note:** This is something Trevor should probably implement once we finish this ticket so that we can get some feedback/complaints on our library.

* `vopen_modified.c`
   - `crypto_vsign_open_modified()`

* `vsign_modified.c`
    - `crypto_vsign_modified()`

**Comment by hdevalence** [comment]
>* `curve_sigs.c`
>   - ✓ `curve25519_sign()` → `ed25519_dalek::SecretKey::sign()`
>   - ✓ `curve25519_verify()` → `ed25519_dalek::PublicKey::verify()`
>   - However, both curve25519-java functions operate on curve25519 keys, so **we still need Mongomery x-coordinate → Edwards y-coordinate conversion.**

I believe my branch has this code already, matching Signal's behaviour of forcing the sign bit to zero when converting from the Montgomery u.

**Comment by isislovecruft** [comment]
My latest work on this (still incomplete) is in my `feature/9-vxeddsa-functionality` branch.

**Comment by isislovecruft** [comment]
Once #23 is merged, we'll have everything with a ✓ below:

* ✓ `crypto_verify_32_ref()` → `curve25519_dalek::util::arrays_equal_ct()`
* ✓ `curve25519_sign()` → `ed25519_dalek::SecretKey::sign()`
* ✓ `curve25519_verify()` → `ed25519_dalek::PublicKey::verify()`
* `legendre_is_nonsquare()`
* `elligator()`
* `hash_to_point()`
* `calculate_Bv()`
* `calculate_Bv_and_V()`
* ✓ `fe_isequal(f, g)` → `curve25519_dalek::field::FieldElement::ct_eq()`
* `fe_mont_rhs()`
* ✓ `fe_montx_to_edy()` → ``
* `fe_sqrt()`
* ✓ `ge_isneutral()` → `curve25519_dalek::curve::ExtendedPoint.is_identity()`
* ✓ `ge_is_small_order()` → `curve25519_dalek::curve::ExtendedPoint.is_small_order()`
* `ge_montx_to_p2()` (*Note:* We don't have this yet, but @hdevalence's code somewhere else has the previously mentioned utility for checking satisfiability of the curve equation.)
* `ge_montx_to_p3()` (*Note:* Same as above.)
* ✓ `ge_neg()` → `impl<'a> Neg for &'a ExtendedPoint`, etc.
* ✓ `ge_p3_to_montx()` We might have this in `decompress_montgomery()` in @hdevalence's `montgomery-x-format` branch.
* ✓ `ge_scalarmult()` → `curve25519_dalek::ExtendedPoint.scalar_mult()`
* ✓ `ge_scalarmult_cofactor()` Somewhere, both @hdevalence and I have separate implementations, but neither is merged yet.
* `curve25519_keygen()` *Note:* We used to have this in some of my old code before the release and we should probably just reanimate that corpse.
* ✓ `crypto_sign_open_modified()` → `ed25519_dalek::PublicKey.verify()`
* `sc_clamp()`
* ✓ `sc_cmov()` → `curve25519_dalek::scalar::Scalar.conditional_assign()`
* ✓ `sc_neg()` → `curve25519_dalek::scalar::Scalar.neg()`
* `crypto_sign_modified()`
* `crypto_usign_open_modified()`
* `crypto_usign_modified()`
* ✓ `print_vector()` → `impl Debug for Vec<T>`
* ✓ `print_bytes()` → `impl Debug for [u8]`
* ✓ `print_fe()` → `impl Debug for FieldElement`
* `crypto_vsign_open_modified()`
* `crypto_vsign_modified()`

The remaining tasks are field element square roots, curve25519 keys and masking, and elligator2 (#8).

**Comment by hdevalence** [comment]
@isislovecruft Looking through this, it looks like the only things we're missing are:

1. Elligator for Ed25519
2. Scalar clamping

How do you want to move forward?

**Comment by hdevalence** [comment]
Closing this for now, we can reopen it later if need be.

**Comment by goldenMetteyya** [comment]
@hdevalence Has any progress on this been made?

thanks

**Comment by david415** [comment]
I would also very likely make use of this if you would kindly implement it.
